# main menu navigation
menu:
  Home: /
  About: /about
  links: http://c.qoco.cn
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: haojen

user:
  name: QOCO
  avatar: /images/ianli.png
  location: In the shenzhen
  description: 这个世界可以很酷
  footnotes: #footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: Haojen/Claudia-theme-blog # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png


